export const TASK_CARD_TAGS = {
  TASK: "TASK",
  BUG: "BUG",
  LOW_PRIORITY: "LOW_PRIORITY",
  HIGH_PRIORITY: "HIGH_PRIORITY",
  URGENT: "URGENT",
} as const;

export const TASK_CARD_TAG_COLORS = {
  [TASK_CARD_TAGS.TASK]: "#3498db",
  [TASK_CARD_TAGS.BUG]: "#f1c40f",
  [TASK_CARD_TAGS.LOW_PRIORITY]: "#2ecc71",
  [TASK_CARD_TAGS.HIGH_PRIORITY]: "#e67e22",
  [TASK_CARD_TAGS.URGENT]: "#c0392b",
};

export const TASK_CARD_TAG_LABELS = {
  [TASK_CARD_TAGS.TASK]: "Tarefa",
  [TASK_CARD_TAGS.BUG]: "Bug",
  [TASK_CARD_TAGS.LOW_PRIORITY]: "Baixa prioridade",
  [TASK_CARD_TAGS.HIGH_PRIORITY]: "Alta prioridade",
  [TASK_CARD_TAGS.URGENT]: "Urgente",
};

export const CARD_TAG_OPTIONS = [
  {
    value: TASK_CARD_TAGS.TASK,
    label: TASK_CARD_TAG_LABELS[TASK_CARD_TAGS.TASK],
  },
  {
    value: TASK_CARD_TAGS.BUG,
    label: TASK_CARD_TAG_LABELS[TASK_CARD_TAGS.BUG],
  },
  {
    value: TASK_CARD_TAGS.LOW_PRIORITY,
    label: TASK_CARD_TAG_LABELS[TASK_CARD_TAGS.LOW_PRIORITY],
  },
  {
    value: TASK_CARD_TAGS.HIGH_PRIORITY,
    label: TASK_CARD_TAG_LABELS[TASK_CARD_TAGS.HIGH_PRIORITY],
  },
  {
    value: TASK_CARD_TAGS.URGENT,
    label: TASK_CARD_TAG_LABELS[TASK_CARD_TAGS.URGENT],
  },
];
